import {
  createDefaultOwnerProfile,
  createEmptyMemoryCheckpoint,
  GLOBAL_ORCHESTRATOR_ACTOR_ID,
  OWNER_ACTOR_ID,
  createCatActorId,
} from '../actors.js';
import {
  appendCoreActivity,
  appendCoreTrace,
  upsertCoreActor,
  upsertCoreApprovalBinding,
  upsertCoreArtifact,
  upsertCoreContainer,
  upsertCoreCheckpoint,
  upsertCoreConversation,
  upsertCoreLane,
  upsertCoreMission,
  upsertCoreOutcome,
  upsertCoreParticipant,
  upsertCoreProject,
  upsertCoreRun,
  upsertCoreSegment,
  upsertCoreSession,
  upsertCoreTransportBinding,
  upsertCoreTurn,
  upsertCoreWorkItem,
} from './records.js';
import {
  addDurableMemory,
  createBotBinding,
  listDurableMemoryBySubject,
  removeBotBinding,
  removeDurableMemory,
  updateDurableMemory,
} from './memoryBindings.js';
import {
  patchOwnerProfile,
  upsertCoreTask,
  writeApprovalDecision,
} from './taskControls.js';
import {
  createDefaultOrchestratorActor,
  createOwnerActor,
} from './shared.js';
import { buildApprovalQueue } from '../approvalQueue.js';
import type {
  BotBindingRecord,
  CatsCoreState,
  CoreTaskRecord,
  DurableMemoryRecord,
  DurableMemorySubjectType,
  OwnerProfileRecord,
} from '../types.js';
import { CATS_CORE_STATE_VERSION } from '../types.js';
import type {
  CoreActorWriteInput,
  CoreActivityWriteInput,
  CoreApprovalBindingWriteInput,
  CoreApprovalWriteInput,
  CoreArtifactWriteInput,
  CoreCheckpointWriteInput,
  CoreContainerWriteInput,
  CoreConversationWriteInput,
  CoreLaneWriteInput,
  CoreMissionWriteInput,
  CoreOutcomeWriteInput,
  CoreParticipantWriteInput,
  CoreProjectWriteInput,
  CoreRunWriteInput,
  CoreSegmentWriteInput,
  CoreSessionWriteInput,
  CoreTransportBindingWriteInput,
  CoreTaskWriteInput,
  CoreTraceWriteInput,
  CoreTurnWriteInput,
  CoreWorkItemWriteInput,
  OwnerProfilePatchInput,
} from './inputs.js';

export {
  addDurableMemory,
  appendCoreActivity,
  appendCoreTrace,
  createBotBinding,
  createCatActorId,
  createDefaultOwnerProfile,
  createEmptyMemoryCheckpoint,
  GLOBAL_ORCHESTRATOR_ACTOR_ID,
  listDurableMemoryBySubject,
  OWNER_ACTOR_ID,
  patchOwnerProfile,
  removeBotBinding,
  removeDurableMemory,
  updateDurableMemory,
  upsertCoreActor,
  upsertCoreApprovalBinding,
  upsertCoreArtifact,
  upsertCoreCheckpoint,
  upsertCoreContainer,
  upsertCoreConversation,
  upsertCoreLane,
  upsertCoreMission,
  upsertCoreOutcome,
  upsertCoreParticipant,
  upsertCoreProject,
  upsertCoreRun,
  upsertCoreSegment,
  upsertCoreSession,
  upsertCoreTask,
  upsertCoreTransportBinding,
  upsertCoreTurn,
  upsertCoreWorkItem,
  writeApprovalDecision,
};
export type {
  BotBindingRecord,
  CoreActorWriteInput,
  CoreActivityWriteInput,
  CoreApprovalBindingWriteInput,
  CoreApprovalWriteInput,
  CoreArtifactWriteInput,
  CoreCheckpointWriteInput,
  CoreContainerWriteInput,
  CoreConversationWriteInput,
  CoreLaneWriteInput,
  CoreMissionWriteInput,
  CoreOutcomeWriteInput,
  CoreParticipantWriteInput,
  CoreProjectWriteInput,
  CoreRunWriteInput,
  CoreSegmentWriteInput,
  CoreSessionWriteInput,
  CoreTransportBindingWriteInput,
  CoreTaskRecord,
  CoreTaskWriteInput,
  CoreTraceWriteInput,
  CoreTurnWriteInput,
  CoreWorkItemWriteInput,
  DurableMemoryRecord,
  DurableMemorySubjectType,
  OwnerProfilePatchInput,
  OwnerProfileRecord,
};
export { buildApprovalQueue };

export function createDefaultCoreState(): CatsCoreState {
  const updatedAt = new Date().toISOString();
  const ownerProfile = createDefaultOwnerProfile(updatedAt);

  return {
    version: CATS_CORE_STATE_VERSION,
    updatedAt,
    setupCompleteAt: null,
    ownerProfile,
    guideCat: null,
    assistantPresets: [],
    actors: [
      createOwnerActor(ownerProfile),
      createDefaultOrchestratorActor(updatedAt),
    ],
    participants: [],
    containers: [],
    conversations: [],
    turns: [],
    lanes: [],
    segments: [],
    sessions: [],
    projects: [],
    workItems: [],
    missions: [],
    tasks: [],
    runs: [],
    traces: [],
    checkpoints: [],
    outcomes: [],
    artifacts: [],
    activities: [],
    approvalBindings: [],
    transportBindings: [],
    botBindings: [],
    archives: [],
    durableMemory: [],
  };
}
