export const SHARED_CORE_FIXTURE_TIME = '2026-03-21T01:00:00.000Z';

export function createSharedCoreFixtureBundle() {
  return {
    ownerProfilePatch: {
      displayName: 'Boss Owner',
      decisionPreferences: ['show options first'],
      escalationPreferences: ['pause before external delivery'],
    },
    project: {
      id: 'project-platform-launch',
      title: 'Cats Platform Launch',
      status: 'active',
      ownerActorId: 'actor-owner',
      summary: 'Shared program record for Chat, Work, and Code.',
      repoPath: '/workspace/one-man-digital-company',
      primaryConversationId: 'conversation-system-1',
      createdAt: SHARED_CORE_FIXTURE_TIME,
      metadata: {
        source: 'shared-fixture',
        product: 'platform',
      },
    },
    workItem: {
      id: 'work-item-chat-routing',
      title: 'Land durable room-routing checkpoints',
      status: 'in_progress',
      projectId: 'project-platform-launch',
      conversationId: 'conversation-system-1',
      taskId: 'task-system-1',
      ownerActorId: 'actor-owner',
      assignedActorIds: ['actor-orchestrator-global'],
      summary: 'Minimal shared-core work item for Team 2 follow-up.',
      createdAt: SHARED_CORE_FIXTURE_TIME,
      metadata: {
        source: 'shared-fixture',
        milestone: 'm2',
      },
    },
    mission: {
      id: 'mission-chat-routing',
      managedWorkId: 'work-item-chat-routing',
      conversationId: 'conversation-system-1',
      sourceTurnId: 'turn-system-1',
      sourceLaneId: 'lane-system-1',
      assignedAgentId: 'actor-orchestrator-global',
      title: 'Route the chat follow-up mission',
      status: 'queued',
      summary: 'Baseline mission fixture for shared-core projections.',
      createdAt: SHARED_CORE_FIXTURE_TIME,
      metadata: {
        source: 'shared-fixture',
        runId: 'run-system-1',
      },
    },
    transportBinding: {
      id: 'transport-binding-system-1',
      platform: 'telegram',
      direction: 'bidirectional',
      conversationId: 'conversation-system-1',
      participantId: null,
      agentId: 'actor-orchestrator-global',
      externalThreadKey: 'bot:boss_cat_bot',
      status: 'active',
      createdAt: SHARED_CORE_FIXTURE_TIME,
      metadata: {
        source: 'shared-fixture',
        botName: 'boss_cat_bot',
      },
    },
    task: {
      id: 'task-system-1',
      title: 'Approve orchestrator dispatch',
      conversationId: 'conversation-system-1',
      summary: 'Core-owned approval task for shared workflow writes.',
      createdAt: SHARED_CORE_FIXTURE_TIME,
    },
    approvalDecision: {
      taskId: 'task-system-1',
      status: 'pending',
      requestedByActorId: 'actor-orchestrator-global',
      notes: 'Need owner confirmation before dispatch.',
    },
    run: {
      id: 'run-system-1',
      title: 'Primary orchestrator dispatch',
      status: 'running',
      conversationId: 'conversation-system-1',
      taskId: 'task-system-1',
      traceId: 'trace-system-1',
      createdAt: SHARED_CORE_FIXTURE_TIME,
      metadata: {
        source: 'shared-fixture',
        mode: 'headless',
      },
    },
    trace: {
      id: 'trace-record-1',
      traceId: 'trace-system-1',
      kind: 'dispatch',
      conversationId: 'conversation-system-1',
      runId: 'run-system-1',
      taskId: 'task-system-1',
      actorId: 'actor-orchestrator-global',
      message: 'Dispatch recorded in the shared core trace log.',
      createdAt: SHARED_CORE_FIXTURE_TIME,
      metadata: {
        source: 'shared-fixture',
        stage: 'dispatch',
      },
    },
    checkpoint: {
      id: 'checkpoint-system-1',
      label: 'owner-gate',
      status: 'open',
      conversationId: 'conversation-system-1',
      runId: 'run-system-1',
      taskId: 'task-system-1',
      sourceTraceId: 'trace-record-1',
      summary: 'Waiting for owner decision.',
      createdAt: SHARED_CORE_FIXTURE_TIME,
      metadata: {
        source: 'shared-fixture',
        gate: true,
      },
    },
    outcome: {
      id: 'outcome-system-1',
      title: 'Blocked for owner',
      status: 'blocked',
      conversationId: 'conversation-system-1',
      runId: 'run-system-1',
      taskId: 'task-system-1',
      summary: 'Run is blocked pending owner approval.',
      recordedAt: SHARED_CORE_FIXTURE_TIME,
      metadata: {
        source: 'shared-fixture',
        severity: 'info',
      },
    },
    artifact: {
      id: 'artifact-system-1',
      title: 'Routing checkpoint export',
      kind: 'document',
      status: 'ready',
      projectId: 'project-platform-launch',
      workItemId: 'work-item-chat-routing',
      conversationId: 'conversation-system-1',
      taskId: 'task-system-1',
      runId: 'run-system-1',
      path: '.cats/artifacts/routing-checkpoint.json',
      mimeType: 'application/json',
      sizeBytes: 512,
      summary: 'Shared artifact reference without chat-local coupling.',
      createdAt: SHARED_CORE_FIXTURE_TIME,
      metadata: {
        source: 'shared-fixture',
        format: 'json',
      },
    },
    activity: {
      id: 'activity-system-1',
      kind: 'approval_requested',
      actorId: 'actor-orchestrator-global',
      projectId: 'project-platform-launch',
      workItemId: 'work-item-chat-routing',
      conversationId: 'conversation-system-1',
      taskId: 'task-system-1',
      runId: 'run-system-1',
      artifactId: 'artifact-system-1',
      message: 'Owner approval requested for the routing checkpoint.',
      createdAt: SHARED_CORE_FIXTURE_TIME,
      metadata: {
        source: 'shared-fixture',
        audience: 'owner',
      },
    },
    approvalBinding: {
      id: 'approval-binding-system-1',
      kind: 'owner_decision',
      approvalTaskId: 'task-system-1',
      subjectKind: 'work_item',
      subjectId: 'work-item-chat-routing',
      projectId: 'project-platform-launch',
      workItemId: 'work-item-chat-routing',
      conversationId: 'conversation-system-1',
      requestedByActorId: 'actor-orchestrator-global',
      requestedForActorId: 'actor-owner',
      createdAt: SHARED_CORE_FIXTURE_TIME,
      metadata: {
        source: 'shared-fixture',
        gate: 'owner-review',
      },
    },
  };
}
