import type {
  WorkGraphBaseDiagnosticKind,
  WorkGraphDiagnostic,
  WorkGraphDiagnosticCategory,
  WorkGraphEvidenceAttachment,
  WorkGraphGateDecorator,
  WorkGraphObjectSummary,
  WorkGraphProjection,
} from "./types";

const NOW = "2026-04-25T03:55:00Z";
const HOURS_AGO = (h: number): string =>
  new Date(Date.parse(NOW) - h * 60 * 60 * 1000).toISOString();

type ObjectFixture = Omit<
  WorkGraphObjectSummary,
  "sourceRecordFamily" | "sourceRecordId"
>;

function withCoreRef(o: ObjectFixture): WorkGraphObjectSummary {
  return { ...o, sourceRecordFamily: o.kind, sourceRecordId: o.id };
}

function diagnosticCategoryFor(
  kind: WorkGraphBaseDiagnosticKind,
): WorkGraphDiagnosticCategory {
  switch (kind) {
    case "broken_fk":
      return "policy";
    case "missing_project_anchor":
    case "missing_planning_execution_bridge":
    case "missing_gate_subject":
      return "anchor";
    case "unanchored_run":
    case "unanchored_evidence":
      return "lineage";
  }
}

type DiagnosticFixture = Omit<WorkGraphDiagnostic, "category">;

const rawObjects: ObjectFixture[] = [
  // Interaction
  {
    id: "conv-marketing",
    kind: "conversation",
    structuralLayer: "interaction",
    title: "#marketing — Black Friday client thread",
    status: "active",
    summary: "Client asking when landing page can ship.",
    attention: "decision_needed",
    ownerRole: "marketing",
    nextAction: "Reply with revised ETA",
    linkedConversationId: null,
    linkedProjectId: "proj-bf",
    linkedWorkItemId: "wi-landing",
    linkedTaskId: null,
    linkedRunId: null,
    updatedAt: HOURS_AGO(1),
  },
  {
    id: "conv-cs",
    kind: "conversation",
    structuralLayer: "interaction",
    title: "CS queue analysis",
    status: "active",
    summary: "Internal thread about response-time investigation.",
    attention: "blocked",
    ownerRole: "customer_support",
    nextAction: "Awaiting metrics export",
    linkedConversationId: null,
    linkedProjectId: "proj-cs",
    linkedWorkItemId: "wi-bottleneck",
    linkedTaskId: null,
    linkedRunId: null,
    updatedAt: HOURS_AGO(6),
  },
  {
    id: "conv-code",
    kind: "conversation",
    structuralLayer: "interaction",
    title: "Frontend code review",
    status: "active",
    summary: "Code review thread for the landing page deploy.",
    attention: "ready_to_review",
    ownerRole: "rd",
    nextAction: "Review pending PR",
    linkedConversationId: null,
    linkedProjectId: "proj-bf",
    linkedWorkItemId: "wi-landing",
    linkedTaskId: "task-deploy",
    linkedRunId: null,
    updatedAt: HOURS_AGO(2),
  },
  {
    id: "agent-marketing",
    kind: "agent",
    structuralLayer: "interaction",
    title: "Marketing Agent",
    status: "active",
    summary: "Owns marketing copy and growth experiments.",
    attention: "none",
    ownerRole: "marketing",
    nextAction: null,
    linkedConversationId: null,
    linkedProjectId: null,
    linkedWorkItemId: null,
    linkedTaskId: null,
    linkedRunId: null,
    updatedAt: HOURS_AGO(48),
  },
  {
    id: "agent-rd",
    kind: "agent",
    structuralLayer: "interaction",
    title: "RD Agent",
    status: "active",
    summary: "Owns code, builds, and deploys.",
    attention: "none",
    ownerRole: "rd",
    nextAction: null,
    linkedConversationId: null,
    linkedProjectId: null,
    linkedWorkItemId: null,
    linkedTaskId: null,
    linkedRunId: null,
    updatedAt: HOURS_AGO(48),
  },

  // Planning
  {
    id: "proj-bf",
    kind: "project",
    structuralLayer: "planning",
    title: "Black Friday landing page",
    status: "active",
    summary: "Refresh the landing page in time for the BF promo.",
    attention: "decision_needed",
    ownerRole: "marketing",
    nextAction: "Decide deploy gate",
    linkedConversationId: "conv-marketing",
    linkedProjectId: null,
    linkedWorkItemId: null,
    linkedTaskId: null,
    linkedRunId: null,
    updatedAt: HOURS_AGO(1),
  },
  {
    id: "proj-cs",
    kind: "project",
    structuralLayer: "planning",
    title: "CS queue investigation",
    status: "active",
    summary: "Why is the CS response time creeping up?",
    attention: "blocked",
    ownerRole: "customer_support",
    nextAction: "Unblock metrics export",
    linkedConversationId: "conv-cs",
    linkedProjectId: null,
    linkedWorkItemId: null,
    linkedTaskId: null,
    linkedRunId: null,
    updatedAt: HOURS_AGO(6),
  },
  {
    id: "proj-rd-hire",
    kind: "project",
    structuralLayer: "planning",
    title: "RD hire (Q2)",
    status: "planned",
    summary: "Define and post a role spec for a senior RD agent.",
    attention: "recently_shipped",
    ownerRole: "rd",
    nextAction: "Post listing",
    linkedConversationId: null,
    linkedProjectId: null,
    linkedWorkItemId: null,
    linkedTaskId: null,
    linkedRunId: null,
    updatedAt: HOURS_AGO(18),
  },
  {
    id: "wi-landing",
    kind: "work_item",
    structuralLayer: "planning",
    title: "Landing page rev 3",
    status: "in_progress",
    summary: "Hero copy + design + deploy.",
    attention: "decision_needed",
    ownerRole: "marketing",
    nextAction: "Approve deploy",
    linkedConversationId: "conv-marketing",
    linkedProjectId: "proj-bf",
    linkedWorkItemId: null,
    linkedTaskId: null,
    linkedRunId: null,
    updatedAt: HOURS_AGO(2),
  },
  {
    id: "wi-bottleneck",
    kind: "work_item",
    structuralLayer: "planning",
    title: "Identify CS response-time bottleneck",
    status: "blocked",
    summary: "Find the slow handoff between humans and agents.",
    attention: "blocked",
    ownerRole: "customer_support",
    nextAction: "Re-run analysis with fresh metrics",
    linkedConversationId: "conv-cs",
    linkedProjectId: "proj-cs",
    linkedWorkItemId: null,
    linkedTaskId: "task-read-transcripts",
    linkedRunId: null,
    updatedAt: HOURS_AGO(6),
  },
  {
    id: "wi-role-spec",
    kind: "work_item",
    structuralLayer: "planning",
    title: "Define RD role spec",
    status: "completed",
    summary: "Role spec doc written and approved.",
    attention: "recently_shipped",
    ownerRole: "rd",
    nextAction: null,
    linkedConversationId: null,
    linkedProjectId: "proj-rd-hire",
    linkedWorkItemId: null,
    linkedTaskId: "task-write-spec",
    linkedRunId: null,
    updatedAt: HOURS_AGO(18),
  },
  {
    id: "wi-orphan",
    kind: "work_item",
    structuralLayer: "planning",
    title: "[orphan] Forgotten retention email idea",
    status: "draft",
    summary: "WorkItem written without a Project anchor.",
    attention: "none",
    ownerRole: null,
    nextAction: null,
    linkedConversationId: null,
    linkedProjectId: null,
    linkedWorkItemId: null,
    linkedTaskId: null,
    linkedRunId: null,
    updatedAt: HOURS_AGO(72),
  },

  // Execution
  {
    id: "task-hero-copy",
    kind: "task",
    structuralLayer: "execution",
    title: "Hero copy v3",
    status: "pending_approval",
    summary: "Draft 3 of the hero copy is ready for review.",
    attention: "decision_needed",
    ownerRole: "marketing",
    nextAction: "Owner decision: approve copy",
    linkedConversationId: "conv-marketing",
    linkedProjectId: "proj-bf",
    linkedWorkItemId: "wi-landing",
    linkedTaskId: null,
    linkedRunId: null,
    updatedAt: HOURS_AGO(3),
  },
  {
    id: "task-deploy",
    kind: "task",
    structuralLayer: "execution",
    title: "Deploy landing page to staging",
    status: "blocked",
    summary: "Failed last attempt; pending owner decision on rollback.",
    attention: "blocked",
    ownerRole: "rd",
    nextAction: "Owner decision: rollback or retry?",
    linkedConversationId: "conv-code",
    linkedProjectId: "proj-bf",
    linkedWorkItemId: "wi-landing",
    linkedTaskId: null,
    linkedRunId: null,
    updatedAt: HOURS_AGO(2),
  },
  {
    id: "task-read-transcripts",
    kind: "task",
    structuralLayer: "execution",
    title: "Read transcripts to find bottleneck",
    status: "blocked",
    summary: "Awaiting metrics refresh.",
    attention: "blocked",
    ownerRole: "customer_support",
    nextAction: "Rerun once metrics export resolves",
    linkedConversationId: "conv-cs",
    linkedProjectId: "proj-cs",
    linkedWorkItemId: "wi-bottleneck",
    linkedTaskId: null,
    linkedRunId: null,
    updatedAt: HOURS_AGO(6),
  },
  {
    id: "task-write-spec",
    kind: "task",
    structuralLayer: "execution",
    title: "Write RD role spec",
    status: "completed",
    summary: "Spec written, owner approved.",
    attention: "recently_shipped",
    ownerRole: "rd",
    nextAction: null,
    linkedConversationId: null,
    linkedProjectId: "proj-rd-hire",
    linkedWorkItemId: "wi-role-spec",
    linkedTaskId: null,
    linkedRunId: null,
    updatedAt: HOURS_AGO(18),
  },
  {
    id: "mission-brief-copywriter",
    kind: "mission",
    structuralLayer: "execution",
    title: "Brief copywriter on Black Friday voice",
    status: "in_progress",
    summary: "Internal coordination, sourced from a marketing turn.",
    attention: "none",
    ownerRole: "marketing",
    nextAction: "Send brief",
    linkedConversationId: "conv-marketing",
    linkedProjectId: "proj-bf",
    linkedWorkItemId: null,
    linkedTaskId: null,
    linkedRunId: null,
    updatedAt: HOURS_AGO(4),
  },
  {
    id: "run-copy-1",
    kind: "run",
    structuralLayer: "execution",
    title: "Hero copy v3 generation",
    status: "in_progress",
    summary: "Marketing agent drafting copy v3.",
    attention: "none",
    ownerRole: "marketing",
    nextAction: null,
    linkedConversationId: "conv-marketing",
    linkedProjectId: null,
    linkedWorkItemId: null,
    linkedTaskId: "task-hero-copy",
    linkedRunId: null,
    updatedAt: HOURS_AGO(3),
  },
  {
    id: "run-deploy-1",
    kind: "run",
    structuralLayer: "execution",
    title: "Staging deploy attempt #1",
    status: "failed",
    summary: "Bundle build failed on dependency resolution.",
    attention: "failed",
    ownerRole: "rd",
    nextAction: "Owner decision on rollback path",
    linkedConversationId: "conv-code",
    linkedProjectId: null,
    linkedWorkItemId: null,
    linkedTaskId: "task-deploy",
    linkedRunId: null,
    updatedAt: HOURS_AGO(2),
  },
  {
    id: "run-write-spec-1",
    kind: "run",
    structuralLayer: "execution",
    title: "Role spec drafting run",
    status: "completed",
    summary: "Spec drafted and approved.",
    attention: "recently_shipped",
    ownerRole: "rd",
    nextAction: null,
    linkedConversationId: null,
    linkedProjectId: null,
    linkedWorkItemId: null,
    linkedTaskId: "task-write-spec",
    linkedRunId: null,
    updatedAt: HOURS_AGO(18),
  },
  {
    id: "run-unanchored",
    kind: "run",
    structuralLayer: "execution",
    title: "[unanchored] Stray exploration run",
    status: "completed",
    summary: "Standalone run with no anchor.",
    attention: "none",
    ownerRole: null,
    nextAction: null,
    linkedConversationId: null,
    linkedProjectId: null,
    linkedWorkItemId: null,
    linkedTaskId: null,
    linkedRunId: null,
    updatedAt: HOURS_AGO(40),
  },

  // Evidence (cross-cutting; structuralLayer: null)
  {
    id: "art-mockup",
    kind: "artifact",
    structuralLayer: null,
    title: "hero-mockup.png",
    status: "ready",
    summary: "Design mockup for the landing page.",
    attention: "none",
    ownerRole: "rd",
    nextAction: null,
    linkedConversationId: "conv-code",
    linkedProjectId: "proj-bf",
    linkedWorkItemId: "wi-landing",
    linkedTaskId: "task-deploy",
    linkedRunId: null,
    updatedAt: HOURS_AGO(12),
  },
  {
    id: "art-role-spec",
    kind: "artifact",
    structuralLayer: null,
    title: "rd-role-spec.md",
    status: "ready",
    summary: "Approved RD role spec.",
    attention: "none",
    ownerRole: "rd",
    nextAction: null,
    linkedConversationId: null,
    linkedProjectId: "proj-rd-hire",
    linkedWorkItemId: "wi-role-spec",
    linkedTaskId: "task-write-spec",
    linkedRunId: "run-write-spec-1",
    updatedAt: HOURS_AGO(18),
  },
  {
    id: "act-deploy-failure",
    kind: "activity",
    structuralLayer: null,
    title: "Deploy run failed (auto-recorded)",
    status: "recorded",
    summary: "Recorded by orchestrator after run-deploy-1 failed.",
    attention: "failed",
    ownerRole: "rd",
    nextAction: "Investigate dependency resolution",
    linkedConversationId: "conv-code",
    linkedProjectId: "proj-bf",
    linkedWorkItemId: "wi-landing",
    linkedTaskId: "task-deploy",
    linkedRunId: "run-deploy-1",
    updatedAt: HOURS_AGO(2),
  },
  {
    id: "out-deploy",
    kind: "outcome",
    structuralLayer: null,
    title: "Deploy run-deploy-1 outcome",
    status: "failed",
    summary: "Outcome record for the failed deploy run.",
    attention: "failed",
    ownerRole: "rd",
    nextAction: null,
    linkedConversationId: "conv-code",
    linkedProjectId: null,
    linkedWorkItemId: null,
    linkedTaskId: "task-deploy",
    linkedRunId: "run-deploy-1",
    updatedAt: HOURS_AGO(2),
  },

  // Gates (cross-cutting; structuralLayer: null)
  {
    id: "ab-hero-copy",
    kind: "approval_binding",
    structuralLayer: null,
    title: "Review gate on Hero copy v3",
    status: "pending",
    summary: "review_gate binding the hero-copy task.",
    attention: "decision_needed",
    ownerRole: "marketing",
    nextAction: "Owner reviews copy",
    linkedConversationId: "conv-marketing",
    linkedProjectId: "proj-bf",
    linkedWorkItemId: "wi-landing",
    linkedTaskId: "task-hero-copy",
    linkedRunId: null,
    updatedAt: HOURS_AGO(3),
  },
  {
    id: "ab-deploy",
    kind: "approval_binding",
    structuralLayer: null,
    title: "Owner decision on deploy rollback",
    status: "pending",
    summary: "owner_decision binding the deploy task.",
    attention: "decision_needed",
    ownerRole: "rd",
    nextAction: "Decide rollback vs retry",
    linkedConversationId: "conv-code",
    linkedProjectId: "proj-bf",
    linkedWorkItemId: "wi-landing",
    linkedTaskId: "task-deploy",
    linkedRunId: null,
    updatedAt: HOURS_AGO(2),
  },
];

const evidenceAttachments: WorkGraphEvidenceAttachment[] = [
  { evidenceObjectId: "art-mockup", anchorObjectId: "wi-landing", relation: "artifact" },
  { evidenceObjectId: "art-mockup", anchorObjectId: "task-deploy", relation: "artifact" },
  { evidenceObjectId: "art-role-spec", anchorObjectId: "wi-role-spec", relation: "artifact" },
  { evidenceObjectId: "art-role-spec", anchorObjectId: "task-write-spec", relation: "artifact" },
  { evidenceObjectId: "act-deploy-failure", anchorObjectId: "task-deploy", relation: "activity" },
  { evidenceObjectId: "act-deploy-failure", anchorObjectId: "run-deploy-1", relation: "activity" },
  { evidenceObjectId: "out-deploy", anchorObjectId: "run-deploy-1", relation: "outcome" },
  { evidenceObjectId: "out-deploy", anchorObjectId: "task-deploy", relation: "outcome" },
];

const gateDecorators: WorkGraphGateDecorator[] = [
  { gateObjectId: "ab-hero-copy", subjectObjectId: "task-hero-copy", state: "pending" },
  { gateObjectId: "ab-deploy", subjectObjectId: "task-deploy", state: "pending" },
];

const objects: WorkGraphObjectSummary[] = rawObjects.map(withCoreRef);

const rawDiagnostics: DiagnosticFixture[] = [
  {
    id: "diag-1",
    severity: "warning",
    kind: "missing_project_anchor",
    objectId: "wi-orphan",
    message: "WorkItem has no projectId; will not appear under any Project tree.",
  },
  {
    id: "diag-2",
    severity: "warning",
    kind: "unanchored_run",
    objectId: "run-unanchored",
    message: "Run has no taskId, parentRunId, or conversationId.",
  },
  {
    id: "diag-3",
    severity: "error",
    kind: "broken_fk",
    objectId: "run-deploy-1",
    message: "Run references task 'task-deploy' but its conversationId diverges from the task's conversation.",
  },
  {
    id: "diag-4",
    severity: "warning",
    kind: "missing_planning_execution_bridge",
    objectId: "conv-marketing",
    message: "Conversation has linked work but no Task or Mission yet.",
  },
  {
    id: "diag-5",
    severity: "info",
    kind: "missing_gate_subject",
    objectId: null,
    message: "1 historical gate binding (archived) lost its subject; cleanup recommended.",
  },
];

const diagnostics: WorkGraphDiagnostic[] = rawDiagnostics.map((d) => ({
  ...d,
  category: diagnosticCategoryFor(d.kind),
}));

export const MOCK_WORK_GRAPH: WorkGraphProjection = {
  objects,
  evidenceAttachments,
  gateDecorators,
  links: [],
  linksByEndpoint: {},
  diagnostics,
};
